DEMO_PRODUCTS = [
    # ── Electronics ─────────────────────────────────────────────
    {
        "name": "Wireless Headphones",
        "description": "Premium noise-cancelling wireless headphones with 30-hour battery life.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [
            "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=400",
            "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=400",
        ],
    },
    {
        "name": "Mechanical Keyboard",
        "description": "Compact mechanical keyboard with RGB backlighting and Cherry MX switches.",
        "price": 129.99,
        "image_url": "https://images.unsplash.com/photo-1595225476474-87563907a212?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [
            "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400",
            "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=400",
        ],
    },
    {
        "name": "USB-C Hub 7-in-1",
        "description": "7-in-1 USB-C hub with HDMI, 3× USB 3.0, SD card reader, and 100W PD charging.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1625842268584-8f3296236761?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Laptop Stand",
        "description": "Ergonomic aluminum laptop stand with adjustable height for better posture and airflow.",
        "price": 45.00,
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
        "category_slug": "electronics",
        "extra_images": [
            "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=400",
        ],
    },
    {
        "name": "LED Desk Lamp",
        "description": "LED desk lamp with touch dimmer, adjustable color temperature, and USB charging port.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Wireless Mouse",
        "description": "Ergonomic wireless mouse with precision optical tracking and 12-month battery life.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "4K IPS Monitor 27\"",
        "description": "27-inch 4K UHD IPS monitor with 99% sRGB, HDR400, and 144 Hz refresh rate.",
        "price": 349.99,
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a573d5f5ef?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "HD Webcam 1080p",
        "description": "Full HD 1080p webcam with auto-focus, built-in stereo microphone, and privacy cover.",
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Bluetooth Speaker",
        "description": "360° waterproof Bluetooth speaker with 24-hour playtime and deep bass.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Smart Watch",
        "description": "Feature-rich smartwatch with health tracking, GPS, AMOLED display, and 7-day battery.",
        "price": 199.99,
        "image_url": "https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "USB Flash Drive 128GB",
        "description": "High-speed USB 3.0 flash drive with 128 GB capacity and compact design.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Portable Power Bank 20000mAh",
        "description": "20000 mAh power bank with dual USB-A and USB-C output plus pass-through charging.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Noise-Cancelling Earbuds",
        "description": "True wireless earbuds with active noise cancellation, 8-hour playback, and IPX5 rating.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "XL Gaming Mouse Pad",
        "description": "Extra-large gaming desk mat with smooth micro-weave surface and non-slip rubber base.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1616588589676-62b3bd4ff6d2?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "External SSD 1TB",
        "description": "Portable external SSD with 1 TB capacity, USB 3.2 Gen 2, and 1050 MB/s read speed.",
        "price": 109.99,
        "image_url": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Smart LED Bulb",
        "description": "Wi-Fi smart LED bulb with 16 million colors, voice assistant support, and app control.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Laptop Sleeve 15\"",
        "description": "Water-resistant neoprene laptop sleeve with accessory pocket. Fits up to 15.6-inch laptops.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1622473590773-f588134b6ce7?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Portable Mini Projector",
        "description": "1080p portable projector with built-in speaker, HDMI & USB-C, and 120-inch display.",
        "price": 299.99,
        "image_url": "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=400",
        "category_slug": "electronics",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "HDMI 2.1 Cable 2m",
        "description": "Ultra high-speed HDMI 2.1 cable supporting 8K@60Hz and 4K@120Hz.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },
    {
        "name": "Wireless Charging Pad",
        "description": "15W fast wireless charging pad compatible with Qi-enabled smartphones and earbuds.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1614380038791-c6f94282e6fb?w=400",
        "category_slug": "electronics",
        "extra_images": [],
    },

    # ── Clothing ────────────────────────────────────────────────
    {
        "name": "Classic White T-Shirt",
        "description": "100% organic cotton crew-neck t-shirt. Pre-shrunk, soft, and breathable.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400",
        "category_slug": "clothing",
        "extra_images": [
            "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400",
        ],
    },
    {
        "name": "Denim Jacket",
        "description": "Classic slim-fit denim jacket with button closure and chest pockets. Unisex.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        "category_slug": "clothing",
        "is_featured": True,
        "extra_images": [
            "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=400",
        ],
    },
    {
        "name": "Fleece Hoodie",
        "description": "Heavyweight fleece-lined pullover hoodie with kangaroo pocket. Stay warm in style.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Slim Fit Jeans",
        "description": "Stretch slim-fit denim jeans with a modern tapered leg. Available in multiple washes.",
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400",
        "category_slug": "clothing",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Linen Button-Down Shirt",
        "description": "Breathable 100% linen shirt perfect for summer. Relaxed fit with roll-up sleeve tabs.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Cargo Pants",
        "description": "Relaxed-fit cargo pants with 6 pockets and reinforced knees. Utility meets comfort.",
        "price": 54.99,
        "image_url": "https://images.unsplash.com/photo-1624378515195-caa8bd40f8fa?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Piqué Polo Shirt",
        "description": "Classic cotton piqué polo with two-button placket. Business casual ready.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Women's Floral Blouse",
        "description": "Lightweight chiffon blouse with a floral print. V-neck with long sleeves.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1562572159-4efc207f5aff?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Stretch Chinos",
        "description": "Slim-fit stretch chinos with flat front and tapered leg. Wrinkle-resistant cotton blend.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Windbreaker Jacket",
        "description": "Lightweight windbreaker with packable hood and elastic cuffs. Water-repellent shell.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1534214526114-0ea4d47b04f2?w=400",
        "category_slug": "clothing",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Graphic Tee",
        "description": "Oversized cotton graphic t-shirt with vintage print. Unisex street-style staple.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Jogger Sweatpants",
        "description": "French terry jogger pants with elastic waistband and tapered cuff. Ultra-comfortable.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Ribbed Tank Top",
        "description": "Stretch ribbed tank top in a form-fitting silhouette. Pairs with everything.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "High-Waist Yoga Leggings",
        "description": "4-way stretch high-waist leggings with phone pocket. Squat-proof and moisture-wicking.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Slim Blazer",
        "description": "Single-breasted slim-fit blazer in stretch fabric. Office-ready in seconds.",
        "price": 119.99,
        "image_url": "https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=400",
        "category_slug": "clothing",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Turtleneck Sweater",
        "description": "Chunky-knit ribbed turtleneck sweater in merino wool blend. Cozy and chic.",
        "price": 64.99,
        "image_url": "https://images.unsplash.com/photo-1607091084257-1b6cead23c06?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Chino Shorts",
        "description": "Tailored 7-inch inseam chino shorts with belt loops and two side pockets.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Puffer Jacket",
        "description": "Lightweight recycled-fill puffer jacket with packable design and windproof shell.",
        "price": 149.99,
        "image_url": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400",
        "category_slug": "clothing",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Rain Jacket",
        "description": "Seam-sealed waterproof rain jacket with removable hood and pit-zip ventilation.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1534214526114-0ea4d47b04f2?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },
    {
        "name": "Oxford Button-Down Shirt",
        "description": "Classic Oxford cloth button-down shirt. Slim fit, point collar, and chest pocket.",
        "price": 54.99,
        "image_url": "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=400",
        "category_slug": "clothing",
        "extra_images": [],
    },

    # ── Shoes ────────────────────────────────────────────────────
    {
        "name": "Running Sneakers",
        "description": "Lightweight running shoes with responsive foam midsole and breathable mesh upper.",
        "price": 99.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "shoes",
        "is_featured": True,
        "extra_images": [
            "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400",
        ],
    },
    {
        "name": "Canvas Slip-Ons",
        "description": "Classic canvas slip-on sneakers with elastic gusset. Lightweight and easy to wear.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Leather Chelsea Boots",
        "description": "Full-grain leather Chelsea boots with elastic side panels and pull-on tab.",
        "price": 149.99,
        "image_url": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400",
        "category_slug": "shoes",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Waterproof Hiking Boots",
        "description": "GORE-TEX waterproof hiking boots with Vibram outsole and ankle support.",
        "price": 139.99,
        "image_url": "https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Leather Loafers",
        "description": "Hand-stitched penny loafers in genuine leather. Slip-on comfort meets elegance.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Ankle Boots",
        "description": "Block-heeled ankle boots in faux suede with side zip closure. Versatile and stylish.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Sport Sandals",
        "description": "Adjustable sport sandals with arch support and quick-dry webbing straps.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1573588028698-f4759befb09a?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Low-Top Sneakers",
        "description": "Minimalist leather low-top sneakers with cushioned insole. Clean everyday style.",
        "price": 74.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Athletic Cross-Trainers",
        "description": "Versatile cross-training shoes with stability sole and breathable knit upper.",
        "price": 84.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Oxford Dress Shoes",
        "description": "Cap-toe Oxford dress shoes in polished calf leather with leather sole.",
        "price": 159.99,
        "image_url": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400",
        "category_slug": "shoes",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Platform Sneakers",
        "description": "Chunky-sole platform sneakers with 4 cm lift and lace-up front. Bold statement shoes.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Backless Mules",
        "description": "Square-toe backless mules in vegan leather. Effortlessly chic.",
        "price": 54.99,
        "image_url": "https://images.unsplash.com/photo-1596703263926-eb0762ee17e4?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Rubber Rain Boots",
        "description": "Tall waterproof rubber rain boots with insulated lining. Keep feet dry all day.",
        "price": 64.99,
        "image_url": "https://images.unsplash.com/photo-1503944168849-8bf86875bbd8?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "High-Top Basketball Shoes",
        "description": "Cushioned high-top basketball shoes with ankle collar support and traction outsole.",
        "price": 119.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Slip-On Knit Sneakers",
        "description": "Sock-fit knit slip-on sneakers with memory foam insole. Maximum daily comfort.",
        "price": 54.99,
        "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Flip Flops",
        "description": "EVA foam flip flops with contoured arch support and textured footbed. Beach essentials.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Wedge Espadrilles",
        "description": "Canvas wedge espadrilles with a 6 cm jute-wrapped wedge and ankle tie.",
        "price": 64.99,
        "image_url": "https://images.unsplash.com/photo-1602828695978-8b07b7e5a4f5?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Desert Boots",
        "description": "Suede desert boots with crepe rubber sole. Casual and timeless.",
        "price": 99.99,
        "image_url": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Trail Running Shoes",
        "description": "Aggressive-lug trail running shoes with rock plate and waterproof upper.",
        "price": 124.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },
    {
        "name": "Flat Moccasins",
        "description": "Hand-stitched suede moccasins with shearling lining. Ultimate cozy slip-ons.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400",
        "category_slug": "shoes",
        "extra_images": [],
    },

    # ── Accessories ─────────────────────────────────────────────
    {
        "name": "RFID Leather Wallet",
        "description": "Slim bifold wallet in genuine leather with RFID-blocking technology and 8 card slots.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Polarized Sunglasses",
        "description": "Polarized UV400 sunglasses with titanium frame and scratch-resistant lenses.",
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
        "category_slug": "accessories",
        "is_featured": True,
        "extra_images": [
            "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
        ],
    },
    {
        "name": "Canvas Backpack",
        "description": "Durable canvas backpack with padded 15\" laptop compartment and water-resistant coating.",
        "price": 54.99,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Minimalist Wrist Watch",
        "description": "Analog watch with stainless steel case, sapphire crystal glass, and genuine leather strap.",
        "price": 119.99,
        "image_url": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400",
        "category_slug": "accessories",
        "is_featured": True,
        "extra_images": [
            "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=400",
        ],
    },
    {
        "name": "Structured Baseball Cap",
        "description": "6-panel structured baseball cap with embroidered logo and adjustable snapback closure.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Wool Ribbed Beanie",
        "description": "Chunky ribbed beanie in 100% merino wool. Warm, soft, and year-round stylish.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1576231843894-47c26a6b02de?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Braided Leather Belt",
        "description": "Braided full-grain leather belt with antique brass buckle. Sizes 28–44.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Silk Infinity Scarf",
        "description": "Lightweight 100% silk infinity scarf with vibrant print. Wear as scarf, headband, or wrap.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Large Canvas Tote Bag",
        "description": "Heavy-duty canvas tote with interior zip pocket and reinforced handles. 20 L capacity.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Leather Crossbody Bag",
        "description": "Compact crossbody bag in pebbled leather with adjustable strap and gold hardware.",
        "price": 69.99,
        "image_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
        "category_slug": "accessories",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Compact Travel Umbrella",
        "description": "Wind-resistant compact umbrella with auto-open/close and Teflon coating. Fits any bag.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "EDC Key Organizer",
        "description": "Aluminum everyday carry key organizer holding up to 10 keys. Quiet and pocket-friendly.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1526547541286-73a7aaa58f3e?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Phone Wallet Case",
        "description": "Magnetic phone wallet case with 3 card slots. Compatible with MagSafe.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Business Laptop Bag 15\"",
        "description": "Professional laptop bag with padded laptop compartment, trolley sleeve, and shoulder strap.",
        "price": 74.99,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Memory Foam Neck Pillow",
        "description": "Ergonomic memory foam travel neck pillow with machine-washable velvet cover.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Packing Cubes Set 4pc",
        "description": "Set of 4 lightweight packing cubes in S/M/L/XL. Double-zip and mesh top.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Passport & Card Holder",
        "description": "RFID-blocking passport holder with slots for 6 cards and a boarding pass sleeve.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Knit Fingerless Gloves",
        "description": "Touchscreen-compatible merino knit fingerless gloves. Type without removing.",
        "price": 21.99,
        "image_url": "https://images.unsplash.com/photo-1576231843894-47c26a6b02de?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Leather Wristlet Clutch",
        "description": "Zip-around wristlet clutch in vegan leather. Fits phone, cards, and keys.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },
    {
        "name": "Aviator Sunglasses",
        "description": "Classic aviator sunglasses with metal frame and gradient mirror lenses. UV400 protection.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400",
        "category_slug": "accessories",
        "extra_images": [],
    },

    # ── Sports & Fitness ─────────────────────────────────────────
    {
        "name": "Non-Slip Yoga Mat",
        "description": "6mm thick eco-friendly TPE yoga mat with alignment lines and carry strap. 183 × 61 cm.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1601925228740-9b6dfed47aab?w=400",
        "category_slug": "sports-fitness",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Resistance Bands Set 5pc",
        "description": "Set of 5 latex resistance bands with handles, ankle straps, and door anchor.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Adjustable Dumbbell Pair",
        "description": "Space-saving adjustable dumbbells from 2–25 kg with quick-change dial system.",
        "price": 149.99,
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
        "category_slug": "sports-fitness",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Speed Jump Rope",
        "description": "Adjustable speed jump rope with ball-bearing handles and 3 m steel-core cable.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "High-Density Foam Roller",
        "description": "High-density EVA foam roller for muscle recovery and deep-tissue massage. 60 cm.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1601925228740-9b6dfed47aab?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Doorframe Pull-Up Bar",
        "description": "No-drill doorframe pull-up bar with foam grips. Supports up to 150 kg.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Gym Gloves",
        "description": "Padded weight-lifting gym gloves with wrist wrap support. Machine washable.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Insulated Sports Water Bottle 1L",
        "description": "Double-wall insulated stainless steel water bottle. Keeps cold 24 h, hot 12 h.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Running Phone Armband",
        "description": "Reflective running armband with touchscreen window. Fits phones up to 6.9\".",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Smart Fitness Tracker Band",
        "description": "Slim fitness tracker with heart rate, SpO2, sleep tracking, and 14-day battery.",
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400",
        "category_slug": "sports-fitness",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Ab Roller Wheel",
        "description": "Dual-wheel ab roller with extra-wide design and non-slip handles for core training.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Cast Iron Kettlebell 16kg",
        "description": "Single-piece cast iron kettlebell with powder-coat finish. Competition-standard width handle.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Compression Running Socks",
        "description": "Graduated compression socks (15–20 mmHg) for improved circulation during long runs.",
        "price": 16.99,
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Microfibre Gym Towel",
        "description": "Ultra-absorbent quick-dry microfibre gym towel with snap hook. 40 × 80 cm.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1549060279-7e168fcee0c2?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Push-Up Handles Board",
        "description": "Multi-grip push-up board with 4 color-coded positions to target different muscle groups.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1570829460005-c840387bb1ca?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Free-Standing Punching Bag 60cm",
        "description": "Free-standing punching bag on adjustable pillar. Ideal for boxing and HIIT training.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400",
        "category_slug": "sports-fitness",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Wobble Balance Board",
        "description": "Wooden wobble balance board for core strengthening, physiotherapy, and skateboard training.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Yoga Block Set 2pc",
        "description": "Set of 2 high-density foam yoga blocks for improved alignment and deeper stretches.",
        "price": 21.99,
        "image_url": "https://images.unsplash.com/photo-1601925228740-9b6dfed47aab?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Skipping Rope Weighted",
        "description": "1 lb weighted skipping rope with smooth-bearing grips for cardio and coordination.",
        "price": 18.99,
        "image_url": "https://images.unsplash.com/photo-1599058917212-d750089bc07e?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },
    {
        "name": "Resistance Loop Bands 5pc",
        "description": "Set of 5 resistance loop bands in ascending resistance for glutes, hips, and rehabilitation.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=400",
        "category_slug": "sports-fitness",
        "extra_images": [],
    },

    # ── Home & Kitchen ───────────────────────────────────────────
    {
        "name": "French Press Coffee Maker",
        "description": "Heat-resistant borosilicate glass French press with stainless steel plunger. 1 L.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
        "category_slug": "home-kitchen",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Chef's Knife 8\"",
        "description": "German high-carbon stainless steel 8-inch chef's knife with ergonomic handle.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Pre-Seasoned Cast Iron Skillet",
        "description": "10-inch pre-seasoned cast iron skillet. Works on all stovetops including induction.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400",
        "category_slug": "home-kitchen",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Bamboo Cutting Board",
        "description": "Eco-friendly bamboo cutting board with juice groove and handle. 40 × 28 cm.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1515516089376-88db1e26e9c0?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Glass Electric Kettle 1.7L",
        "description": "1.7 L borosilicate glass electric kettle with LED ring and auto shut-off.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Countertop Toaster Oven",
        "description": "12-function toaster oven with convection fan, 30 L capacity, and preset programs.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Air Fryer 5.5L",
        "description": "Digital air fryer with 5.5 L basket, 8 pre-set programs, and rapid hot-air circulation.",
        "price": 119.99,
        "image_url": "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400",
        "category_slug": "home-kitchen",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "High-Power Blender 1000W",
        "description": "1000W blender with 6-blade stainless assembly, 1.5 L tritan jar, and pulse function.",
        "price": 69.99,
        "image_url": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Burr Coffee Grinder",
        "description": "Conical burr coffee grinder with 18 grind settings, 200 g hopper, and stainless burrs.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Stainless Steel Mixing Bowls 5pc",
        "description": "Set of 5 stainless steel mixing bowls with non-slip base and lid. Nest for storage.",
        "price": 32.99,
        "image_url": "https://images.unsplash.com/photo-1574518546034-b42f4b65fb76?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Ceramic Non-Stick Frying Pan 28cm",
        "description": "PTFE-free ceramic non-stick frying pan. PFOA-free, oven-safe to 220°C, induction-ready.",
        "price": 37.99,
        "image_url": "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Multi-Cooker Pressure Pot 6qt",
        "description": "7-in-1 electric multi-cooker: pressure cooker, slow cooker, rice cooker, steamer, and more.",
        "price": 89.99,
        "image_url": "https://images.unsplash.com/photo-1585515320310-259814833e62?w=400",
        "category_slug": "home-kitchen",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Digital Kitchen Scale",
        "description": "Precision digital kitchen scale, 0.1 g to 5 kg, with tare function and LCD display.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1574518546034-b42f4b65fb76?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Knife Block Set 6pc",
        "description": "6-piece German steel knife set with chef, bread, carving, utility, paring knives + block.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1593618998160-e34014e67546?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Silicone Kitchen Tool Set 6pc",
        "description": "Heat-resistant silicone tool set: spatula, ladle, slotted spoon, tongs, whisk, and brush.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1574518546034-b42f4b65fb76?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Ceramic Baking Dish 3pc",
        "description": "Set of 3 oven-safe ceramic baking dishes in S/M/L. Dishwasher safe.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1574518546034-b42f4b65fb76?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Handheld Electric Mixer",
        "description": "250W 5-speed handheld mixer with beaters, dough hooks, and turbo boost button.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Herb & Salad Scissors",
        "description": "5-blade herb scissors with cleaning comb. Snip herbs, salad greens, and pizza.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1515516089376-88db1e26e9c0?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Rotating Spice Rack 20-Jar",
        "description": "Countertop rotating spice rack with 20 glass jars, labels, and chalk marker.",
        "price": 37.99,
        "image_url": "https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },
    {
        "name": "Collapsible Dish Drying Rack",
        "description": "Collapsible stainless steel dish rack with drainage tray. Folds flat for storage.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1574518546034-b42f4b65fb76?w=400",
        "category_slug": "home-kitchen",
        "extra_images": [],
    },

    # ── Books & Stationery ───────────────────────────────────────
    {
        "name": "Dotted Bullet Journal A5",
        "description": "200-page thick dotted A5 bullet journal. Numbered pages, index, and lay-flat binding.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1592312040408-ee41c88a1ba2?w=400",
        "category_slug": "books-stationery",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Fountain Pen Set",
        "description": "Brass fountain pen with medium nib, converter, and 6 ink cartridges. Ideal for calligraphy.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Watercolor Paint Set 48 Colors",
        "description": "Professional-grade watercolor set with 48 vibrant pans, mixing palette, and 3 brushes.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Artist Colored Pencils 72pc",
        "description": "72 oil-based artist colored pencils with premium pigment cores in a metal tin.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Sticky Notes Mega Bundle",
        "description": "300-sheet sticky notes bundle in 4 sizes and 10 colors. Strong adhesive.",
        "price": 9.99,
        "image_url": "https://images.unsplash.com/photo-1586282391129-76a6df230234?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Weekly Planner 2026 Hardcover",
        "description": "Dated 2026 hardcover planner with weekly spreads, habit trackers, and lay-flat binding.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1558021212-51b6ecfa0db9?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Brush Calligraphy Starter Set",
        "description": "Brush calligraphy set with 2 beginner brush pens, ink, nib, and practice guide.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Sketch Book A4 140gsm",
        "description": "80-sheet A4 sketchbook with 140 gsm acid-free white paper. Hardcover spiral bound.",
        "price": 16.99,
        "image_url": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Gel Pen Rainbow Set 20pc",
        "description": "20-piece gel pen set with glitter, metallic, pastel, and neon ink. 0.5 mm tip.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Bamboo Desk Organizer",
        "description": "5-compartment bamboo desk organizer for pens, scissors, sticky notes, and phone.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Flash Card Set 200pc",
        "description": "200 blank ruled index flash cards on a binder ring. Study tool for all ages.",
        "price": 8.99,
        "image_url": "https://images.unsplash.com/photo-1586282391129-76a6df230234?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Washi Tape Set 20 Rolls",
        "description": "20 decorative washi tape rolls in assorted widths and patterns for journaling and crafts.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1586282391129-76a6df230234?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Drawing Tablet 10\"",
        "description": "Slim 10-inch graphics drawing tablet with 8192 pressure levels and battery-free pen.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400",
        "category_slug": "books-stationery",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Origami Paper 500 Sheets",
        "description": "500-sheet origami paper pack in 50 colors and patterns. 15 × 15 cm.",
        "price": 9.99,
        "image_url": "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Mechanical Pencil Set 4pc",
        "description": "Set of 4 drafting mechanical pencils in 0.3/0.5/0.7/0.9 mm with lead refills.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Pastel Highlighter Set 12pc",
        "description": "12 dual-tip pastel highlighters (chisel + fine). No bleed-through on most paper.",
        "price": 11.99,
        "image_url": "https://images.unsplash.com/photo-1586282391129-76a6df230234?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Cork Bulletin Board 60×90cm",
        "description": "Self-healing cork bulletin board in a pinewood frame. Includes 30 map pins.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1586282391129-76a6df230234?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Adjustable Book Stand",
        "description": "Aluminum adjustable book stand with page clips. 7 height settings. Anti-slip base.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1592312040408-ee41c88a1ba2?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Magnetic Bookmarks 20pc",
        "description": "20-piece magnetic bookmark set in assorted designs. Slim and won't damage pages.",
        "price": 8.99,
        "image_url": "https://images.unsplash.com/photo-1592312040408-ee41c88a1ba2?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },
    {
        "name": "Leather Journal A5 Refillable",
        "description": "Vintage handmade leather journal with refillable inserts and antique clasp. A5.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1592312040408-ee41c88a1ba2?w=400",
        "category_slug": "books-stationery",
        "extra_images": [],
    },

    # ── Beauty & Personal Care ───────────────────────────────────
    {
        "name": "Vitamin C Face Serum 30ml",
        "description": "15% vitamin C serum with hyaluronic acid and niacinamide. Brightens and firms skin.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
        "category_slug": "beauty-personal-care",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Hydrating Day Face Cream SPF15",
        "description": "Lightweight SPF15 day cream with ceramides and shea butter. For all skin types.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Organic Shea Lip Balm Set 4pc",
        "description": "Set of 4 organic shea butter lip balms in tinted berry, vanilla, coconut, and mint.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1586495777744-4e6b8f919922?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Sulfate-Free Shampoo Bar",
        "description": "Concentrated sulfate-free shampoo bar for normal-to-dry hair. Lasts 80 washes.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Activated Charcoal Face Wash 150ml",
        "description": "Deep-cleansing activated charcoal gel face wash with tea tree oil. Pore-minimising.",
        "price": 18.99,
        "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Coconut Body Lotion 300ml",
        "description": "Non-greasy coconut and aloe vera body lotion with 24-hour moisture lock.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Essential Oil Ultrasonic Diffuser",
        "description": "400 ml ultrasonic aroma diffuser with 7-color LED, mist control, and timer.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1519638399535-1b036603ac77?w=400",
        "category_slug": "beauty-personal-care",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Rose Quartz Jade Face Roller",
        "description": "Dual-ended rose quartz face roller to reduce puffiness and boost serum absorption.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Bamboo Toothbrush Set 4pc",
        "description": "Set of 4 biodegradable bamboo toothbrushes with charcoal-infused soft bristles.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Korean Sheet Mask Set 10pc",
        "description": "10-piece Korean sheet mask set targeting hydration, brightening, and firming.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Biotin Hair Growth Serum 60ml",
        "description": "Biotin and caffeine scalp serum to strengthen hair and reduce breakage.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Coffee Body Scrub 200g",
        "description": "Exfoliating coffee and coconut oil body scrub. Smooths skin and reduces cellulite appearance.",
        "price": 18.99,
        "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Professional Makeup Brush Set 12pc",
        "description": "12-piece vegan makeup brush set with synthetic fibres and bamboo handles.",
        "price": 27.99,
        "image_url": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400",
        "category_slug": "beauty-personal-care",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Gold Under-Eye Patches 30 Pairs",
        "description": "30 pairs of collagen and gold under-eye patches to depuff and reduce dark circles.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Sonic Electric Face Cleanser",
        "description": "3-speed sonic facial cleansing brush with replaceable silicone head. Waterproof.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Argan Oil Deep Hair Mask 250ml",
        "description": "Nourishing argan oil hair mask for dry and damaged hair. Leave-in or rinse-out.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Nail Care Manicure Kit 9pc",
        "description": "9-piece stainless steel nail care kit: clippers, file, pusher, cleaner, and case.",
        "price": 16.99,
        "image_url": "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "SPF 50 Mineral Sunscreen 100ml",
        "description": "Broad-spectrum SPF 50 mineral sunscreen. Reef-safe, fragrance-free, no white cast.",
        "price": 21.99,
        "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Whipped Shea Body Butter 200g",
        "description": "Whipped shea and mango butter body cream. Dense, ultra-rich moisture for dry skin.",
        "price": 23.99,
        "image_url": "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },
    {
        "name": "Micellar Cleansing Water 400ml",
        "description": "Gentle micellar water removes make-up, cleanses, and tones in one step. No rinsing.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400",
        "category_slug": "beauty-personal-care",
        "extra_images": [],
    },

    # ── Toys & Games ─────────────────────────────────────────────
    {
        "name": "Wooden Building Blocks 100pc",
        "description": "100-piece natural wood building block set in 9 shapes. Develops spatial reasoning.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "1000-Piece Jigsaw Puzzle",
        "description": "1000-piece premium jigsaw puzzle with illustrated world map design. 68 × 47 cm finished.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Remote Control Off-Road Car",
        "description": "1:16 scale RC off-road car with 4WD, 30+ km/h top speed, and 2.4 GHz remote.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400",
        "category_slug": "toys-games",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Strategy Board Game",
        "description": "Award-winning 2–4 player strategy board game of resource trading. Ages 10+.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Classic Creative Building Set 500pc",
        "description": "500-piece classic interlocking brick building set. Compatible with major brands.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Magnetic Drawing Board",
        "description": "A4 magnetic drawing board with erase slider. Mess-free drawing for kids 3+.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Jenga Classic Stacking Game",
        "description": "Classic 54-block hardwood Jenga stacking tower. Hours of family fun.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Premium Playing Cards 2 Decks",
        "description": "2 decks of casino-grade 100% plastic playing cards. Washable and durable.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Handcrafted Wooden Chess Set",
        "description": "Folding wooden chess board with weighted pieces. Includes checkers on reverse side.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Speed Cube 3×3",
        "description": "Competition-speed 3×3 rubik-style cube with magnetic core and smooth corner cutting.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Kids Toy Kitchen Playset",
        "description": "Realistic kitchen playset with sink, stove, oven, and 25 food and utensil accessories.",
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Foam Dart Blaster Kit",
        "description": "Manual foam dart blaster with 30 soft darts, safety glasses, and bandolier.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1574180566232-aaad1b5b8450?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Interactive Globe with LED",
        "description": "Illuminated educational globe with country quiz, capitals, and ocean floor detail.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Kinetic Sand Art Kit 1kg",
        "description": "1 kg moldable kinetic sand with 10 molds and sculpting tools. Indoor sensory play.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Marble Run Race Track 100pc",
        "description": "100-piece transparent track marble run set with 4 marbles. Build and race.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Realistic Dinosaur Figures Set 12pc",
        "description": "12 hand-painted realistic dinosaur figures: T-Rex, Triceratops, Brachiosaurus, and more.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Puzzle Cube Brain Teaser Set 5pc",
        "description": "Set of 5 puzzle cubes in varying difficulty. Great for cognitive development.",
        "price": 29.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Extra-Thick Foam Play Mat 9 Tiles",
        "description": "9-tile interlocking EVA foam play mat. 1.5 cm thick, non-toxic, easy to clean.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Storytelling Prompt Cards 64pc",
        "description": "64-card storytelling prompt deck for creative writing and family storytelling games.",
        "price": 16.99,
        "image_url": "https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },
    {
        "name": "Bug Catcher Exploration Kit",
        "description": "Kids bug catching kit with magnifier jar, tweezers, net, and field guide. Ages 4+.",
        "price": 16.99,
        "image_url": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400",
        "category_slug": "toys-games",
        "extra_images": [],
    },

    # ── Automotive ───────────────────────────────────────────────
    {
        "name": "Dash Cam 4K Front & Rear",
        "description": "4K front + 1080p rear dual-channel dash cam with night vision, GPS, and Wi-Fi.",
        "price": 99.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Universal Car Phone Mount",
        "description": "Magnetic air-vent car phone mount. 360° rotation. Compatible with all phones.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Portable Jump Starter 2000A",
        "description": "2000A peak lithium jump starter for up to 8L petrol / 6L diesel engines. Built-in flashlight.",
        "price": 79.99,
        "image_url": "https://images.unsplash.com/photo-1613214049841-028981952e86?w=400",
        "category_slug": "automotive",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Cordless Car Vacuum Cleaner",
        "description": "15000 Pa cordless handheld car vacuum with HEPA filter and flexible crevice tool.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1614926857083-7be149266cda?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Digital Tyre Pressure Gauge",
        "description": "LCD digital tyre pressure gauge 0–100 PSI with auto-off and LED torch.",
        "price": 14.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "RGB LED Interior Car Lights Kit",
        "description": "App-controlled RGB car interior ambient light strip with music sync mode.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Car Air Freshener Vent Clips 4pc",
        "description": "Set of 4 vent clip car air fresheners in ocean, vanilla, lavender, and pine scent.",
        "price": 12.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Seat Back Organiser",
        "description": "Foldable seat-back organiser with tablet holder, drinks pockets, and storage pouches.",
        "price": 22.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Leather Steering Wheel Cover",
        "description": "Universal 37–38 cm microfibre leather steering wheel cover. Anti-slip grip.",
        "price": 17.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Emergency Road Safety Kit",
        "description": "Complete emergency kit: jumper cables, reflective triangle, first-aid, poncho, and torch.",
        "price": 44.99,
        "image_url": "https://images.unsplash.com/photo-1613214049841-028981952e86?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "All-Weather Rubber Floor Mats 4pc",
        "description": "Heavy-duty rubber car floor mats with anti-slip nibs. Universal fit, easy to trim.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Bluetooth FM Transmitter",
        "description": "Bluetooth 5.0 FM transmitter with QC3.0 fast charge, hands-free call, and EQ modes.",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Pre-Cut Ceramic Window Tint Film",
        "description": "5% VLT nano-ceramic window tint roll. Heat rejection 99% IR blocking. 50 × 300 cm.",
        "price": 32.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Foam Cannon Car Wash Gun",
        "description": "Adjustable foam cannon for pressure washer. 1 L soap tank, brass nozzle.",
        "price": 34.99,
        "image_url": "https://images.unsplash.com/photo-1614926857083-7be149266cda?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Wireless Parking Sensor Kit 4-Probe",
        "description": "4-probe wireless reverse parking sensor with LCD display and buzzer.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Foldable Windshield Sun Shade",
        "description": "Reflective accordion-fold windshield sun shade. Blocks heat and UV rays. Universal fit.",
        "price": 19.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "OBD2 Bluetooth Diagnostic Scanner",
        "description": "Bluetooth OBD2 scanner reads/clears fault codes. Works with iOS and Android apps.",
        "price": 49.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "is_featured": True,
        "extra_images": [],
    },
    {
        "name": "Cooling Gel Car Seat Cushion",
        "description": "Honeycomb cooling gel seat cushion with non-slip base. Reduces pressure and heat.",
        "price": 39.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Rooftop Cargo Bag 15 cu.ft",
        "description": "Waterproof 15 cu.ft rooftop cargo bag. Universal strap fit, no rack needed.",
        "price": 59.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
    {
        "name": "Hybrid Wiper Blades Pair",
        "description": "Aerodynamic hybrid wiper blades with all-season rubber coating. Pair 24\"/18\".",
        "price": 24.99,
        "image_url": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400",
        "category_slug": "automotive",
        "extra_images": [],
    },
]
